### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Prune2** [Hyperclaw79/PokeBall-SelfBot#135]
Uh 

Traceback (most recent call last):
  File "launcher.py", line 2, in <module>
    from pokeball import PokeBall
  File "C:\Users\User\Desktop\PokeBall-SelfBot-master\PokeBall-SelfBot-master\pokeball.py", line 167
    return f"{name} -> {number} -> {level}"

Keep having this error when I run run.bat

**Comment by Hyperclaw79** [comment]
Check your Python version using `python --version`. It should be 3.6.
