### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ashishlodhi1234** [Hyperclaw79/PokeBall-SelfBot#155]
C:\Users\DELL\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master>py -3 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 18, in <module>
    bot = PokeBall(config_path, guild_path, pokelist_path, pokenames_path)
  File "C:\Users\DELL\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master\pokeball.py", line 42, in __init__
    self.auto_catcher = self.configs["auto_catcher"]
KeyError: 'auto_catcher'

C:\Users\DELL\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master>timeout -1

Press any key to continue ...

**Comment by ashishlodhi1234** [comment]
C:\Users\DELL\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master>py -3 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 18, in <module>
    bot = PokeBall(config_path, guild_path, pokelist_path, pokenames_path)
  File "C:\Users\DELL\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master\pokeball.py", line 42, in __init__
    self.auto_catcher = self.configs["auto_catcher"]
KeyError: 'auto_catcher'

C:\Users\DELL\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master>timeout -1

Press any key to continue ...

**Comment by ashishlodhi1234** [comment]
> C:\Users\DELL\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master>py -3 launcher.py
> Traceback (most recent call last):
> File "launcher.py", line 18, in
> bot = PokeBall(config_path, guild_path, pokelist_path, pokenames_path)
> File "C:\Users\DELL\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master\pokeball.py", line 42, in **init**
> self.auto_catcher = self.configs["auto_catcher"]
> KeyError: 'auto_catcher'
> 
> C:\Users\DELL\Downloads\PokeBall-SelfBot-master\PokeBall-SelfBot-master>timeout -1
> 
> Press any key to continue ...
