### ISSUE TITLE
Help again... xD

### ISSUE THREAD

**Issue by pazzaro** [Hyperclaw79/PokeBall-SelfBot#55]
the downloading worked and i pasted both the bots token and mine but after i launch launcher.py in terminal it says "KeyError: 'MY BOTS TOKEN BGAGUAGB ' i tried copy pasting it again im using incognito mode on my main and normal window on the bot.

**Comment by pazzaro** [comment]
It showed this after i launched: 

Traceback (most recent call last):
  File "launcher.py", line 17, in <module>
    alter_config(config_path)
  File "/Users/Nate/Desktop/PokeBall-SelfBot-master/secret.py", line 6, in alter_config
    configs = json.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 17 column 37 (char 384)
Unknown:PokeBall-SelfBot-master Nate$ 
Unknown:PokeBall-SelfBot-master Nate$ 
Unknown:PokeBall-SelfBot-master Nate$ python3 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 17, in <module>
    alter_config(config_path)
  File "/Users/Nate/Desktop/PokeBall-SelfBot-master/secret.py", line 6, in alter_config
    configs = json.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 17 column 37 (char 384)

**Comment by pazzaro** [comment]
i also tried modifying the secret.py by removing os eviron and taking it back

**Comment by pazzaro** [comment]
IN the white least section i removed the numbers before the / and tried it and the numbers after the slash both showed these:

Traceback (most recent call last):
  File "launcher.py", line 18, in <module>
    bot = PokeBall(config_path, guild_path, pokelist_path, pokenames_path)
  File "/Users/Nate/Desktop/PokeBall-SelfBot-master/pokeball.py", line 23, in __init__
    super().__init__()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 118, in __init__
    self.loop = asyncio.get_event_loop() if loop is None else loop
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 599, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 617, in new_event_loop
    return self._loop_factory()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/unix_events.py", line 56, in __init__
    super().__init__(selector)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 61, in __init__
    super().__init__()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 250, in __init__
    and bool(os.environ.get('PYTHONASYNCIODEBUG'))))
AttributeError: 'list' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 510, in __del__
    warnings.warn("unclosed event loop %r" % self, ResourceWarning,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 272, in __repr__
    self.is_closed(), self.get_debug()))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1469, in get_debug
    return self._debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'

**Comment by Hyperclaw79** [comment]
> both the bots token and mine, KeyError: 'MY BOTS TOKEN BGAGUAGB '

Can you censor a few character in your token and paste it here? In the exact same manner as you pasted in `secret.py`. Paste that whole line.

Also, looks like your other error is a missing comma in `config.json`. Post that too so that I can tell you where to add the comma.

**Comment by pazzaro** [comment]
![screen shot 2018-05-29 at 12 46 07 am](https://user-images.githubusercontent.com/39652543/40623459-d8daf22e-62d9-11e8-89c8-937df09b61d8.png)

**Comment by pazzaro** [comment]
![screen shot 2018-05-29 at 12 48 11 am](https://user-images.githubusercontent.com/39652543/40623579-2a2c0cf8-62da-11e8-84bc-a727616b65b8.png)
