### ISSUE TITLE
Bot not running

### ISSUE THREAD

**Issue by JohnnyMustang** [Hyperclaw79/PokeBall-SelfBot#79]
C:\Users\Johnny\Downloads\PokeBall-SelfBot-master>py -3 launcher.py
Traceback (most recent call last):
  File "C:\Users\Johnny\AppData\Roaming\Python\Python36\site-packages\discord\http.py", line 257, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "C:\Users\Johnny\AppData\Roaming\Python\Python36\site-packages\discord\http.py", line 216, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "launcher.py", line 19, in <module>
    bot.run()
  File "C:\Users\Johnny\Downloads\PokeBall-SelfBot-master\pokeball.py", line 51, in run
    super().run(self.configs['token'], bot=False)
  File "C:\Users\Johnny\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 580, in run
    return task.result()
  File "C:\Users\Johnny\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 500, in _silence_gathered
    fut.result()
  File "C:\Users\Johnny\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 487, in start
    yield from self.login(*args, bot=bot)
  File "C:\Users\Johnny\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 353, in login
    yield from self.http.static_login(token, bot=bot)
  File "C:\Users\Johnny\AppData\Roaming\Python\Python36\site-packages\discord\http.py", line 261, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.

The setup is succesful, but I get this error when I double click the "run" file. 

I get the following when I open the run file as admin 

C:\WINDOWS\system32>py -3 launcher.py
C:\Program Files\Python36\python.exe: can't open file 'launcher.py': [Errno 2] No such file or directory

C:\WINDOWS\system32>timeout -1

**Comment by JohnnyMustang** [comment]
Okay, I did a dummy. I initially had trouble with this bot so I downloaded pokecatcher and that one worked so I was using that one, but now I tried installing this one again and I forgot to input my token. 

I did that now and I'm not getting that error, but I don't get any logs either, the bot doesn't initialise.

**Comment by Hyperclaw79** [comment]
Post your `config.json` while censoring a few characters in your token.

**Comment by JohnnyMustang** [comment]
Not sure what the problem was, but it's working fine now. Sorry for opening up the issue!
